version: '3.9'

services:
  wordpress:
    image: wordpress:latest
    container_name: start-wordpress
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/start-theme
    restart: always

  db:
    image: mysql:latest
    container_name: start-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
